[build]
  command = "npm run build"
  publish = "dist/movie-tracker"

# Uncomment this section to use Netlify Dev
# [dev]
#   command = "npm run start"
#   port = 4200
#   publish = "dist/movie-tracker"

# Redirect all routes to index.html for Angular routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200